### ISSUE TITLE
Can not get is_cuda attribute from LazyTensor

### ISSUE THREAD

**Issue by diggerdu** [rentruewang/aioway#5] opened 2021-11-30 09:43 UTC

**Comment by rentruewang** [comment] 2021-11-30 10:06
Noted. Will add this in the near future!

**Comment by rentruewang** [comment] 2021-11-30 15:39
I'm going to close this in favor of #6. While both this and #6 are caused by the same issue and this came first, I forgot about that and answered why those `property`es cannot be supported in the current implementation [here](https://github.com/rentruewang/koila/issues/6#issuecomment-982746636).

**Closed as completed by rentruewang** 2021-11-30 15:39 UTC
